### ISSUE TITLE
How to correctly cite your project

### ISSUE THREAD

**Issue by 123yonghu** [leocsato/detector_mw#1]
I am currently conducting a study about malware detection in which I am using your project on GitHub. In order to correctly cite your work in my own project, I wanted to ask what is the right way to do this.
Do you have a specific citation format or any other citation requirements? I would appreciate if you could provide a citation template that meets your expectations.

**Comment by leocsato** [comment]
Hello, @123yonghu 
Sorry it took so long to reply, I didn't receive an alert about this issue.

I don't have a particular citation format, but I can give you a suggestion:
"Leonardo C Sato. Deep learning in computer security: Intelligent detection of malicious code. Federal University of Technology - Paraná. Pato Branco, 2018."

Also, I will share with you this link:
https://repositorio.utfpr.edu.br/jspui/handle/1/14613

It is in Portuguese, but it has more information about this work. The associated PDF file is the main paper.
There is a citation template ("_Citação_") in that page as well.
You could use it, if it is more appropriate for your research.
I would suggest replacing the title, work type and university parts with translations, though.

**Comment by 123yonghu** [comment]
Thanks a lot!
